name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting your first issue. You make this project even better!'
        pr-message: 'You did it! You submitted an enhancement to this project to make it even better!'
